---
title: "FE570 - Homework #2"
subtitle: "I pledge my honor that I have abided by the Stevens Honor System."
author: "Sid Bhatia"
date: "2023-10-16"
output: pdf_document
---

## Problem 2.1

#### 1.

```{r}
# Load necessary packages.
library(xts)
library(highfrequency)

# Load in data set.
options(digits.secs=3)
absolute_path <- 'C:/Users/sbhatia2/My Drive/University/Academics/Semester V/FE570 - Market Microstructure and Trading Strategies/FE570 - Homework/FE570 - Homework #2/'
load(paste(absolute_path, "sampleTQdata.RData", sep = ""))

# Added to remove warnings about time zone mismatch.
Sys.setenv(TZ='GMT')

head(tqdata)
tail(tqdata)
```

##### i.

How many trades are in the dataset?

```{r}
# Retrieve number of trades by counting number of rows in dataset.
num_of_trades <- nrow(tqdata)
num_of_trades
```

As seen above, there are 8153 trades in the dataset.

##### ii.

Plot the trade prices $p_t$ and the best-bid $b_t$ and best-ask prices $a_t$ for the entire dataset.

```{r}
# Convert dataset to data frame for easier access.
TQ_df <- data.frame(Date = index(tqdata), tqdata)
head(TQ_df)

# Retrieve the 'asks' or 'offers' from data frame.
asks <- as.numeric(TQ_df$OFR)
head(asks)

# Retrieve 'bids' from data frame.
bids <- as.numeric(TQ_df$BID)
head(bids)

# Compute the 'mid' or middle price between bid and ask.
mids <- (bids + asks) * 0.5
head(mids)

# Establish minimum and maximum prices quoted.
p_min <- min(as.numeric(TQ_df$PRICE))
p_max <- max(as.numeric(TQ_df$PRICE))

p_min
p_max

# Plot trade prices and respective best-bid and best-ask prices using the mid price.
plot(as.numeric(TQ_df$PRICE), col = "green", type = "l", ylab = "Trade Price", 
    xlab = "Trade Number", main = "Price Fluctuation", ylim = c(p_min - 0.2, p_max + 0.2))
lines(mids, type = "l", col = "blue")
```

##### iii.

Do the same as in ii) but only for trades with counts 100:200 (100th trade to 200th trade).

```{r}
# Retrieve sliced data frame from 100 to 200 trades.
TQ_df_sliced <- data.frame(tqdata[100:200])


```