---
title: "FE570 - Homework #4"
subtitle: "I pledge my honor that I have abided by the Stevens Honor System."
author: "Sid Bhatia"
date: "2023-12-04"
output: pdf_document
---

**Glosten-Harris model**. The Glosten-Harris model is an improvement of the Roll model which takes into account:

- Bid-ask bounce: $cd_t$
- Price impact: $\lambdax_t$

In this model, trade price $p_t$ is given by:

$$p_t = m_t + cd_t + \lambda x_t$$

where the efficient price $m_t$ contains a price impact $\lambda x_{t-1}$ due to the previous trade:

$$m_t = m_{t-1} + \lambda x_{t-1} + \mu_t$$

Here, $u_t$ are iid random variables with mean zero and variance $\sigma_u^2$, similar to the Roll model.

Note that here, $x_t$ are *signed* trade sizes: positive for buy, negative for sell.

## Question

Calibrate the $\lambda$, $c$ parameters of this model using the provided TAQ dataset. The dataset provided contains trades and quotes for KO (Coca-Cola) on 1-Mar-2022.

For this analysis it is important to exclude from the analysis large trades at the start and end of the trading session. For example, keep only trades
with time stamps between 10:00 - 14:00.

## Hints

First, we need the signed trade sizes $x_t = d_t |x_t|$, where $d_t$ are the trade indicators and $|x_t|$ are the absolute errors of the trade size which are available in the TAQ data as `r tqdata$SIZE`.

We get the trade indicators using the `r getTradeDirection(tqdata)` which is the implementation of the Lee-Ready mid-point criterion.

```{r}
# Load necessary packages.
library(xts)
library(highfrequency)

# Load in data set.
options(digits.secs=3)

absolute_path <- 'C:/Users/sbhatia2/My Drive/University/Academics/Semester V/FE570 - Market Microstructure and Trading Strategies/FE570 - Homework/FE570 - Homework #4/'
load(paste(absolute_path, "taqdata_KO_20220301v1.RData", sep = ""))

# Added to remove warnings about time zone mismatch.
Sys.setenv(TZ='GMT')

head(tqdata)
tail(tqdata)

# Convert DT column to datetime format.
tqdata$DT <- as.POSIXct(tqdata$DT, format="%Y-%m-%d %H:%M:%OS")

head(tqdata$DT)

# Calculate mid-price (efficient price) at the time of the trade.
tqdata$MID_PRICE <- (tqdata$BID + tqdata$OFR) / 2

# Get trade directions using Lee-Ready mid-point criterion.
tqdata$TRADE_DIRECTION <- getTradeDirection(tqdata)

head(tqdata$TRADE_DIRECTION)

# Calculate signed-size x_t based on d_t * |x_t|.
tqdata$SIGNED_SIZE <- tqdata$TRADE_DIRECTION * tqdata$SIZE

head(tqdata$SIGNED_SIZE)

# Shift MID_PRICE and SIGNED_SIZE to get previous values.
tqdata$Lagged_MID_PRICE <- lag.xts(tqdata$MID_PRICE, k = 1)
tqdata$Lagged_SIGNED_SIZE <- lag.xts(tqdata$SIGNED_SIZE, k = 1)

head(tqdata)

# Prepare the dependent variable (p_t - m_t).
tqdata$PT_MINUS_MT <- tqdata$PRICE - tqdata$MID_PRICE

# Linear regression to estimate lambda and c.
model <- lm(PT_MINUS_MT ~ SIGNED_SIZE + TRADE_DIRECTION, data = tqdata)

# Output the model summary to get the estimates of lambda and c
summary(model)
```




